# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import os
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)

        ht = 1080
        wt = 1920
        MainWindow.resize(wt, ht)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.pixmap = QPixmap('home.png')
        self.label_20.setPixmap(self.pixmap)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1225+60, 180-100, 851, 100))
        self.label.setStyleSheet("font: 75pt \"Colonna MT\";\n"
                                 "color: #bbbbbb;")
        self.label.setObjectName("label")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect( 1250, 270-100 , 361, 90))
        self.label_2.setStyleSheet("font: 40pt \"Colonna MT \";\n"
                                   "color: #bbbbbb;")
        self.label_2.setObjectName("label_2")

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1230, 400-140, 400, 90))
        self.pushButton_5.setStyleSheet("QPushButton{background-color:#bbbbbb;\n"
                                      "font: 24pt \"Showcard Gothic\";\n"
                                      "border-radius:30px;\n"
                                      "padding:3px; \n color: #ff3232;}"
                                      "QPushButton:hover{\n"
                                      "background-color:#ff4c4c;\n"
                                      "color: white;\n"
                                      "}\n"
                                      )
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect( 1230, 400, 400,90))
        self.pushButton.setStyleSheet("QPushButton{background-color:#bbbbbb;\n"
                                      "font: 24pt \"Showcard Gothic\";\n"
                                      "border-radius:30px;\n"
                                      "padding:3px; \n color: #ff3232;}"
                                      "QPushButton:hover{\n"
                                      "background-color:#ff4c4c;\n"
                                      "color: white;\n"
                                      "}\n"
                                      )
        self.pushButton.setObjectName("pushButton")


        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect( 1230, 540, 400,90))
        self.pushButton_2.setStyleSheet("QPushButton{background-color: #bbbbbb;\n"
                                        "font: 24pt \"Showcard Gothic\";\n"
                                        "border-radius:30px; \n color: #ff3232;}"
                                        "QPushButton:hover{\n"
                                        "background-color:#ff4c4c;\n"
                                        "color: white;\n"
                                        "}\n"
                                        )
        self.pushButton_2.setObjectName("pushButton_2")


        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1230, 680, 400,90))
        self.pushButton_3.setStyleSheet("QPushButton{background-color: #bbbbbb;\n"
                                        "font: 24pt \"Showcard Gothic\";\n"
                                        "border-radius:30px; \n color: #ff3232;}"
                                        "QPushButton:hover{\n"
                                        "background-color:#ff4c4c;\n"
                                        "color: white;\n"
                                        "}\n")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect( 1230, 820, 400,90))
        self.pushButton_4.setStyleSheet("QPushButton{background-color:#bbbbbb ;\n"
                                        "font: 24pt \"Showcard Gothic\";\n"
                                        "border-radius:30px; \n color: #ff3232;}"
                                        "QPushButton:hover{\n"
                                        "background-color:#ff4c4c;\n"
                                        "color: white;\n"
                                        "}\n")
        self.pushButton_4.setObjectName("pushButton_4")



        MainWindow.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MENU"))
        self.label_2.setText(_translate("MainWindow", "Difficulty Level"))
        self.pushButton_5.setText(_translate("MainWindow", "Normal"))
        self.pushButton.setText(_translate("MainWindow", "Medium"))
        self.pushButton_2.setText(_translate("MainWindow", "Hard"))
        self.pushButton_3.setText(_translate("MainWindow", "Controls"))
        self.pushButton_4.setText(_translate("MainWindow", "EXIT"))

        self.pushButton_5.clicked.connect(self.fun1)
        self.pushButton.clicked.connect(self.fun2)
        self.pushButton_2.clicked.connect(self.fun3)
        self.pushButton_3.clicked.connect(self.fun4)
        self.pushButton_4.clicked.connect(self.exit)


    def fun1(self):
        import bs1

    def fun2(self):
        import bs2
    def fun3(self):
        import bs3

    def fun4(self):
        import GC_1
        # MainWindow.hide()
        # os.system("start Level3/main.exe")
        # sys.exit()

    def exit(self):
        sys.exit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # MainWindow.show()
    MainWindow.showMaximized()
    sys.exit(app.exec_())
